feat: Add process to install specific version.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,12 +4,42 @@ author: "ryohidaka"
 
 description: "Custom action to set up SQLite environment."
 
+inputs:
+  version:
+    description: "SQLite version to install (optional)"
+    required: false
+    default: ""
+
 runs:
   using: "composite"
   steps:
-    - name: Install latest SQLite version
+    - name: Check available SQLite versions
+      id: check-versions
       run: |
-        echo "Installing the latest version"
+        sudo apt-get update
+        available_versions=$(apt-cache showpkg sqlite3 | grep -Eo '3\.[0-9]+\.[0-9]+' | sort -V | uniq | tr '\n' ',')
+        available_versions=${available_versions%,}
+        echo "Available versions: $available_versions"
+        echo "versions=$available_versions" >> $GITHUB_OUTPUT
+      shell: bash
+
+    - name: Install specified SQLite version
+      if: inputs.version != ''
+      run: |
+        if echo "${{ steps.check-versions.outputs.versions }}" | grep -q "^${{ inputs.version }}$"; then
+          echo "Installing SQLite version ${{ inputs.version }}"
+          sudo apt-get install -y sqlite3=${{ inputs.version }} libsqlite3-dev=${{ inputs.version }}
+          echo "SQLite version ${{ inputs.version }} installed successfully."
+        else
+          echo "Error: Specified version ${{ inputs.version }} is not available"
+          exit 1
+        fi
+      shell: bash
+
+    - name: Install latest SQLite version
+      if: inputs.version == ''
+      run: |
+        echo "No version specified, installing the latest version"
         sudo apt-get install -y sqlite3 libsqlite3-dev
         echo "Latest SQLite version installed successfully."
       shell: bash
